In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3])
a.shape

(4,)

In [3]:
b = np.array(['a','b','c','d','e','A','B','C','D','E'])
b.shape

(10,)

In [5]:
b1 = b[2:7:1]
print(b)
print(b1)
print(b[7])

['a' 'b' 'c' 'd' 'e' 'A' 'B' 'C' 'D' 'E']
['c' 'd' 'e' 'A' 'B']
C


In [6]:
b2 = b[2:7:2]
print(b2)

['c' 'e' 'B']


In [7]:
b3 = b[3:]
print(b3)

['d' 'e' 'A' 'B' 'C' 'D' 'E']


In [9]:
b4=b[:3]
print(b4)

['a' 'b' 'c']


In [10]:
b5 = b[:]
print(b5)

['a' 'b' 'c' 'd' 'e' 'A' 'B' 'C' 'D' 'E']


In [11]:
t = np.array([2,5,7,2,1])
t1 = -t
print(t1)
t2 = sum(t)
print(t2)
t3 = np.mean(t)
print(t3)
t4 = t**2
print(t4)

[-2 -5 -7 -2 -1]
17
3.4
[ 4 25 49  4  1]


In [12]:
z1 = np.array([5,3,6,7])
z2 = np.array([9,4,2,8])
z3 = 5*z1
print(z3)
z4 = np.dot(z1,z2)
print(z4)

[25 15 30 35]
125


In [15]:
def my_dot(a,b):
    x =a.shape[0]
    s = 0
    for i in range(x):
        s = s + a[i]*b[i]
    return s

In [16]:
my_dot(z1,z2)

125

In [18]:
import time
l1 = np.random.rand(1000000)
l2 = np.random.rand(1000000)
time1 = time.time()
lz_1 = my_dot(l1,l2)
time2 = time.time()
tot_time_1 = time2-time1
print(lz_1,tot_time_1)
time3 = time.time()
lz_2 = np.dot(l1,l2)
time4 = time.time()
tot_time_2 = time4-time3
print(lz_2,tot_time_2)


249980.39165505738 0.22646403312683105
249980.39165506174 0.0026590824127197266


In [20]:
X = np.array([[1],[9],[8]])
X[1].shape

(1,)

In [21]:
W1 = [8]
c = np.dot(X[1],W1)
c.shape

()

In [23]:
u = np.zeros((1,5))
print(u.shape,u)
u1 = np.zeros((3,1))
print(u1.shape,u1)
u2 = np.random.random_sample((1,1))
print(u2.shape,u2)

(1, 5) [[0. 0. 0. 0. 0.]]
(3, 1) [[0.]
 [0.]
 [0.]]
(1, 1) [[0.68867606]]


In [24]:
u4 = np.zeros((4,5))
print(u4.shape,u4)

(4, 5) [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
y = np.arange(6).reshape(-1,2)
print(y)
print(y[0,1].shape)
print(y[0,1])

[[0 1]
 [2 3]
 [4 5]]
()
1


In [28]:
print(y[2,1])

5


In [29]:
r1 = np.arange(20).reshape(-1,10)
print(r1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [30]:
r_1 = r1[0,2:7:1]
print(r_1)
r_2 = r1[:,2:7:1]
print(r_2)
r_3 = r1[:,:]
print(r_3)

[2 3 4 5 6]
[[ 2  3  4  5  6]
 [12 13 14 15 16]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [31]:
r_4 = r1[1,:]
print(r_4)
r_5 = r1[1]
print(r_5)

[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]
